export const meta = {
  name: 'build-gitpulse',
  description: 'Build GitPulse - GitHub Trend website with Vue 3 and Cloudflare Pages',
  phases: [
    { title: 'Backend API', detail: 'Cloudflare Pages Functions with Hono' },
    { title: 'Frontend Core', detail: 'Vue 3 pages, components, stores, router' },
    { title: 'Styles and Charts', detail: 'Dark sci-fi theme, ECharts, animations' },
    { title: 'Documentation', detail: 'README, DEPLOYMENT guide, GitHub Actions' },
  ],
}

const BASE = '/Users/huangjingping/i/github-stars'

phase('Backend API')

await agent('You are building the backend API for GitPulse, a GitHub Trend website using Cloudflare Pages Functions. Project root: ' + BASE + '. Create these 7 files: 1) functions/api/_middleware.ts - CORS middleware that adds Access-Control-Allow-Origin: * and handles OPTIONS. 2) functions/api/trending.ts - GET handler for trending repos. Query params: range (today/weekly/monthly), language, topic, page, pageSize, sortBy, search. Returns paginated repos with trend data. Include mock data with 20+ realistic repos. 3) functions/api/repos/[owner]/[repo].ts - GET handler for repo detail with snapshot history. Mock data fallback. 4) functions/api/languages.ts - GET handler for language stats. Mock data fallback. 5) functions/api/topics.ts - GET handler for topic stats. Mock data fallback. 6) functions/api/stats/overview.ts - GET handler for dashboard overview stats. Mock data fallback. 7) functions/api/sync.ts - POST handler for manual GitHub data sync. Requires Authorization header. All handlers use Cloudflare Pages Functions format with onRequest(context) where context.env.DB is the D1 binding. READ types at src/types/index.ts FIRST. Each file must be complete with comprehensive mock data fallbacks using realistic repo data (vercel/next.js, facebook/react, etc). WRITE all 7 files.', { label: 'backend-api', phase: 'Backend API' })

phase('Frontend Core')

await parallel([
  () => agent('Build Vue 3 router, stores, and API service for GitPulse. Project root: ' + BASE + '. READ types at src/types/index.ts first. Create 8 files: 1) src/router/index.ts - Vue Router with 6 lazy-loaded routes: / (Dashboard), /trending (Trending), /repo/:owner/:repo (RepoDetail), /languages (Languages), /topics (Topics), /about (About). 2) src/stores/repos.ts - Pinia store with state: trendingRepos, currentRepo, snapshots, loading, error. Actions: fetchTrending, fetchRepoDetail. 3) src/stores/stats.ts - Pinia store with state: overview, languages, topics, loading. Actions: fetchOverview, fetchLanguages, fetchTopics. 4) src/stores/filters.ts - Pinia store with state: range, language, topic, page, pageSize, sortBy, search. Actions: setRange, setLanguage, setTopic, setPage, setSortBy, setSearch, resetFilters. 5) src/services/api.ts - API service calling /api/* endpoints. Functions: getTrending, getRepoDetail, getLanguages, getTopics, getStatsOverview, triggerSync. 6) src/services/mock.ts - Complete mock data service with 20+ realistic repos and all endpoint data. 7) src/main.ts - Vue app entry installing router and pinia. 8) src/App.vue - Root component with AppHeader and router-view. WRITE all 8 files.', { label: 'frontend-core', phase: 'Frontend Core' }),

  () => agent('Build 6 Vue 3 page components for GitPulse with dark sci-fi dashboard aesthetic. Project root: ' + BASE + '. READ types at src/types/index.ts first. Create: 1) src/views/DashboardView.vue - HeroSection, 5 StatCards, Top 10 repos list, chart areas. 2) src/views/TrendingView.vue - DateRangeTabs, LanguageFilter, TopicTag chips, SearchBar, sort dropdown, RepoTrendCard list with pagination, empty/loading states. 3) src/views/RepoDetailView.vue - Breadcrumb, repo info header, stats row, topic tags, charts for star/fork trends. 4) src/views/LanguagesView.vue - Language stat cards grid, distribution pie chart, click to filter. 5) src/views/TopicsView.vue - Topic stat cards grid, heatmap, click to filter. 6) src/views/AboutView.vue - Data source explanation, ranking algorithm, disclaimer. ALL components must use script setup lang="ts" and style scoped lang="scss". Dark theme: bg #050816, cards #0B1026. Glass morphism, glow borders, responsive max-width 1280px. WRITE all 6 files.', { label: 'frontend-pages', phase: 'Frontend Core' }),

  () => agent('Build 14 reusable Vue 3 components for GitPulse with dark sci-fi UI. Project root: ' + BASE + '. READ types at src/types/index.ts first. Create all with script setup lang="ts" and style scoped lang="scss": 1) src/components/AppHeader.vue - Sticky nav with logo, links (Trending, Languages, Topics, About), glass morphism bg. 2) src/components/HeroSection.vue - Title "Discover What Developers Are Building", subtitle, animated radar background (CSS). 3) src/components/StatCard.vue - Props: title, value, icon, trend, trendValue. Large number, trend arrow, glass card. 4) src/components/RepoTrendCard.vue - Props: repo. Avatar, name, description, language tag, stars, forks, today stars, rank badge, hover glow. 5) src/components/RepoRankList.vue - Props: repos array. Ranked list with top 3 special styling. 6) src/components/LanguageFilter.vue - Props: languages array, selected string. Pill buttons with active glow. 7) src/components/TopicTag.vue - Props: topic, active, count. Small pill with optional count badge. 8) src/components/TrendChart.vue - Props: option, height. ECharts wrapper with dark theme. 9) src/components/RadarBackground.vue - CSS radar scan animation, concentric circles, rotating sweep. 10) src/components/DateRangeTabs.vue - Props: selected. Tabs: Today, Weekly, Monthly. 11) src/components/SearchBar.vue - Search icon, dark input, glow border on focus. 12) src/components/EmptyState.vue - Props: message, icon. Centered layout. 13) src/components/LoadingSkeleton.vue - Props: rows. Animated pulse. 14) src/components/RepoDetailPanel.vue - Props: repo. Info display, stats grid, topic tags. WRITE all 14 files.', { label: 'frontend-components', phase: 'Frontend Core' })
])

phase('Styles and Charts')

await parallel([
  () => agent('Create SCSS styles for GitPulse dark sci-fi theme. Project root: ' + BASE + '. Create 3 files: 1) src/styles/variables.scss - All SCSS variables: colors (bg-primary #050816, bg-secondary #070B1F, bg-card #0B1026, color-blue #38BDF8, color-purple #8B5CF6, color-cyan #22D3EE, color-green #34D399, color-orange #F59E0B), text colors (primary #F8FAFC, secondary #CBD5E1, muted #64748B), border colors, shadows (glow-blue, glow-purple, glow-cyan), layout (max-width 1280px, border-radius 12px), breakpoints, transitions, fonts. Include mixins: glass-card (backdrop-filter blur, bg card, border subtle), glow-border (box-shadow glow), text-gradient (gradient text). 2) src/styles/global.scss - Import variables, CSS reset, body styles (bg-primary, font-sans, text-primary), dark scrollbar, grid background pattern (subtle dots), utility classes, base glass-card class. 3) src/styles/animations.scss - Keyframes: pulse, fadeIn, slideUp, slideIn, radar-sweep, float, glow-pulse, gradient-shift. Radar background styles, grid pattern, code flow particles. WRITE all 3 files.', { label: 'styles', phase: 'Styles and Charts' }),

  () => agent('Create ECharts composable and favicon for GitPulse. Project root: ' + BASE + '. Create 2 files: 1) src/composables/useChart.ts - Import echarts core modules (CanvasRenderer, LineChart, BarChart, PieChart, GridComponent, TooltipComponent, LegendComponent). Export useChart() returning: createStarTrendOption(data) - smooth line chart with gradient fill, createLanguagePieOption(data) - donut chart, createTopicHeatmapOption(data) - bar chart for topics, createTopReposBarOption(data) - horizontal bar chart, createForkTrendOption(data) - line chart. All charts use dark theme (transparent bg, text #CBD5E1, axis lines rgba(56,189,248,0.2), blue/cyan/purple palette). Include mock data generators for each. 2) public/favicon.svg - Simple SVG icon with star/trending arrow, colors #38BDF8 and #8B5CF6, 32x32 viewBox. WRITE both files.', { label: 'charts', phase: 'Styles and Charts' })
])

phase('Documentation')

await agent('Write documentation for GitPulse. Project root: ' + BASE + '. Create 3 files: 1) README.md - Project name GitPulse, description, tech stack (Vue 3 + TypeScript + Vite + Cloudflare Pages + D1), features, quick start, project structure, API endpoints, env vars, MIT license. 2) DEPLOYMENT.md - Extremely detailed step-by-step Cloudflare Pages FREE deployment guide: Prerequisites, Clone repo, Create Pages project (Workers and Pages > Create > Pages > Connect to Git, build settings: Framework Vue, command npm run build, output dist), Create D1 database (Workers and Pages > D1 > Create), Configure D1 binding (Settings > Functions > D1 binding: variable=DB, database=gitpulse-db), Set env vars (GITHUB_TOKEN, SYNC_SECRET), Initialize database (run schema.sql via dashboard SQL editor), First deploy (push triggers auto-deploy), Set up daily sync via GitHub Actions (create workflow, add secrets SYNC_URL and SYNC_SECRET), Custom domain (optional), Verify, Troubleshooting section. 3) .github/workflows/sync.yml - GitHub Actions: runs daily 02:00 UTC, supports workflow_dispatch, POST to sync endpoint with auth, error handling. WRITE all 3 files.', { label: 'documentation', phase: 'Documentation' })
